nodes:
  indexer:
    - name: wazuh-indexer
      ip: 172.20.20.11
      dns:
        - wazuh-indexer
  server:
    - name: wazuh-manager
      ip: 172.20.20.8
      dns:
        - wazuh-manager
  dashboard:
    - name: wazuh-dashboard
      ip: 172.20.20.12
      dns:
        - wazuh-dashboard
